name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build Container
      run: docker build ./ -t salesmonitor.azurecr.io/sales-monitor  
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: salesmonitor
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        login-server: salesmonitor.azurecr.io
    - name: Push image
      run: docker push salesmonitor.azurecr.io/sales-monitor
    
